version: 2.1

orbs: codecov: codecov/codecov@3.2.3
jobs:
  build:
    docker:
      - image: circleci/golang:1.18
    steps:
      - checkout
      - run:
          name: Run tests and coverage
          command: go test -race -coverprofile=coverage.out -covermode=atomic
      - codecov/upload

workflow:
  version: 2.1
  build-test:
    jobs:
      - build
