name: Vulnerability Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  vulncheck:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.23.2'

      - name: Install govulncheck
        run: go install golang.org/x/vuln/cmd/govulncheck@latest

      - name: Verify govulncheck installation
        run: |
          echo "Verifying govulncheck installation..."
          govulncheck --version  # Verify the installation of govulncheck

    # Run the govulncheck tool and check for vulnerabilities
      - name: Run govulncheck and check vulnerabilities
        run: |
          set -e  # Ensure the script fails if any command fails
          echo "Running govulncheck..."
          govulncheck --version  # Verify the installed version of govulncheck
          govulncheck ./... > vuln.txt 2>&1 || echo "govulncheck completed with errors, continue..."
          if [ -s vuln.txt ]; then
            echo "Vulnerabilities found. Printing report..."
            cat vuln.txt
          else
            echo "No vulnerabilities found."
          fi

      # Create summary.md
      - name: Set Summary in Environment Variable
        run: |
          if [ -s vuln.txt ]; then
            echo "## Vulnerabilities Found" > summary.md
            cat vuln.txt >> summary.md
            # Escape newlines to ensure correct formatting for environment variables
            SUMMARY=$(cat summary.md | sed ':a;N;$!ba;s/\n/\\n/g')
            echo "SUMMARY=$SUMMARY" >> $GITHUB_ENV
          else
            echo "No vulnerabilities found" > summary.md
            echo "SUMMARY=No vulnerabilities found" >> $GITHUB_ENV
          fi

      
      - name: Upload vulnerability report
        uses: actions/upload-artifact@v4
        with:
          name: vulnerability-report
          path: vuln.txt

      # Commit and push vuln.txt and summary.md
      - name: Commit and push vuln.txt and summary.md
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add vuln.txt summary.md
          git commit -m "Add vulnerability report and summary"
          git push origin master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}